### ISSUE TITLE
Client does not return `error` when postcode is not found

### ISSUE THREAD

**Issue by corinnebrady** [ideal-postcodes/ideal-postcodes-core#4]
According to the docs, the callback should return both `error` and `addresses`. The issue i'm facing is that `error` is only triggered for account related errors but not for postcode errors. 

For example, using the postcode `ID1 CLIP` error returns a message that includes "No lookups remaining error" (4020). But when the postcode `ID1 KFA` (which should return an error with "Postcode does not exist error" (4040)) `error` is returned as `null` and `addresses` are `null` as well. 

Since postcodes that cause a `4040` code are errors, why is `error` still returning `null`?

**Comment by cblanc** [comment]
Hi there

From a RESTful API perspective, you're 100% correct. If a postcode is a resource, then requesting a non existent postcode would yield a `404` client error status code.

At the time of developing this library, rightly or wrongly, the client wasn't designed to feel like interacting with a RESTful API. Admittedly this additional layer of abstraction occasionally leaks when you're dealing with more obscure errors. However, given an invalid postcode is quite a common outcome, at the time it seemed more natural to handle invalid postcodes like:

```javascript
if (addresses === null) // handle postcode not found
```

rather than:

```
if (error && error.responseCode === 4040) // handle postcode not found
```

So I'd agree from a RESTful standpoint, `404` is an error. But for most integrations it may not be necessary for the clients to understand which error codes to catch - checking for `null` or `Address[]`  and generic error handling for other errors may suffice

Having said that I'll bear this in mind in case this library requires a redesign
